[info]

path_to_dataset: ../data/comm_subset_medicine_dataset.csv

# mysql info
host: localhost
port: 6603
# host: 192.168.33.111
user: root
password: 1234
# password: bio_1

## next parameters
# database: name of mysql database
# path_to_owl: path of owl ontology
# path_to_ontology_db: path of sqlite db or " " if none
# items_prefix: prefix of the ontology
database: entities_sim_med2care_rs

# ---- ONTOLOGIES LIST -------

[CHEBI]
table_name: similarity_chebi
path_to_owl:  ../data/chebi_lite.owl
path_to_ontology_db:  ../data/chebi.db
items_prefix: CHEBI_

[DO]
# database_do: do_sim_med2care_rs

# path_to_owl:  ../data/doid.owl
# path_to_ontology_db:  ../data/doid202005.db
# items_prefix: DOID_

# GO
#database: go_sim_cord_rs

#path_to_owl:  ../data/go.owl
#path_to_ontology_db: ../data/go.db
#items_prefix: GO_    

# HP
# database: hp_sim_cord_rs
# path_to_owl:  ../data/hp.owl
# path_to_ontology_db: ../data/hp.db
# items_prefix: HP_


# COVID
#database: covid_sim_20_200 

#path_to_owl:  ../data/covid19.owl
#path_to_ontology_db:  ../data/covid19.db
#items_prefix: CHEBI_

# this parameter split the dataset of compounds, which is useful when the size of the list is big
n_split_dataset: 5
