[info]

path_to_dataset: ../data/emc_medicine_dataset.csv
# path_to_dataset: ../data/drugbank_medicine_dataset.csv

# mysql info
host: localhost
port: 6603
user: root
password: 1234

## next parameters
# database: name of mysql database
# path_to_owl: path of owl ontology
# path_to_ontology_db: path of sqlite db or " " if none
# items_prefix: prefix of the ontology
database: emc_entities_sim_med2care_rs
# database: drugbank_entities_sim_med2care_rs

# ---- ONTOLOGIES LIST -------

[CHEBI]
table_name: similarity_chebi
path_to_owl:  ../data/ontologies/chebi_lite.owl
path_to_ontology_db:  ../data/ontologies/chebi.db
items_prefix: CHEBI_

# this parameter split the dataset of compounds, which is useful when the size of the list is big
n_split_dataset: 5
