[info]

#path_to_original_json_folder = /path/to/original_data/folder/
#path_to_entities_json_folder =  /path/to/entities_data/folder/

#path_to_csv: /path/to/csv.csv

# n most similar items (1st quartile)
n = .25

# Dataset
#path_to_dataset: /data/metadata_new.csv

# items list separeted by commas. If none is written, all are considered
# by default: chebi, doid, go, hp
# item_prefix: chebi, doid
item_prefix: chebi

# normalized values
normalized: 1

# Ontologies path
path_owl_chebi: ../data/ontologies/chebi_lite.owl
path_owl_doid: ../data/ontologies/doid.owl
path_owl_go: #../data/ontologies/go.owl
path_owl_hp: #../data/ontologies/hp.owl

path_db_chebi: ../data/ontologies/chebi.db
path_db_doid: ../data/ontologies/doid.db
path_db_go: #../data/ontologies/go.db
path_db_hp: #../data/ontologies/hp.db

# mysql info
# host: 172.17.0.2
host: localhost
port: 6603
user: root
password: 1234

# database
database: entities_sim_med2care_rs
tablename: similarity

# Save DS 
# folders (1) results1: test dataset; (2) results: complete dataset
path2ds: ../data/comm_subset_medicine_dataset.csv
path2kb: ../data/results/med2care_rs_kb.csv

# Save metadata about process
path2info: ../data/info_process_kb.txt
