[INFO]
#last update: 2020-01-29
#user: mpato

[PATH]
path_to_dataset: ../data/comm_subset_medicine_dataset.csv
# path_to_dataset: ../data/med2care_rs_kb_chebi_sim_jc_.csv
# path_to_dataset: ../data/med2care_rs_kb_chebi_sim_lin_.csv
# path_to_dataset: ../data/med2care_rs_kb_chebi_sim_morgan_.csv
# path_to_dataset: ../data/med2care_rs_kb_chebi_sim_resnik_.csv
# path_to_dataset: ../data/med2care_rs_kb_chebi_sim_tanimoto_.csv

# path_to_dataset: ../data/comm_use_subset_9k_entities_recsys_dataset_user_item_rating_index_user_item_label.csv
# path_to_dataset: ../data/cheRM_20_200.csv

# Cross-validation folds
cv: 2

# size of the list of recommendations
topk = 5

# n most similar items
n = 5

[DBINFO]
#host: med2care-mysql
#port: 3306
host: localhost
port: 6603
user: root
password: 1234

## next parameters
# database: name of mysql database
# path_to_owl: path of owl ontology
# path_to_ontology_db: path of sqlite db or " " if none
# items_prefix: prefix of the ontology
database: entities_sim_med2care_rs
# ---- ONTOLOGIES LIST -------

# CHEBI

path_to_owl:  ../data/ontologies/chebi_lite.owl
path_to_ontology_db: ../data/ontologies/chebi.db
items_prefix: CHEBI_

# DOID
# database: do_sim_cord_rs
#
# path_to_owl:  ../data/doid.owl
# path_to_ontology_db:  ../data/doid202005.db
# items_prefix: DOID_

# COVID
# database: covid_sim_20_200

# path_to_owl:  ../data/covid19.owl
# path_to_ontology_db:  ../data/covid19.db
# items_prefix: CHEBI_

# similarity metric, you can choose all of them or one
# then write "all", "sim_lin", "sim_resnik", "sim_jc"
# similarity_metric: sim_lin
similarity_metric: all