[info]

#path_to_original_json_folder = /path/to/original_data/folder/
#path_to_entities_json_folder =  /path/to/entities_data/folder/

#path_to_csv: /path/to/csv.csv

# n most similar items (1st quartile)
[QUARTILE]
n = .25

# Dataset
#path_to_dataset: /data/metadata_new.csv

# items list: uncomment item
[ENTITIES]
item_prefix1: chebi
item_prefix2: do
item_prefix3: #go
item_prefix4: #hp

# Ontologies path
[PATH]
path_owl_chebi: /data/ontologies/chebi_lite.owl
path_owl_do: /data/ontologies/doid.owl
path_owl_go: #../data/ontologies/go.owl
path_owl_hp: #../data/ontologies/hp.owl
path_db_chebi: /data/ontologies/chebi.db
path_db_do: /data/ontologies/doid.db
path_db_go: #../data/ontologies/go.db
path_db_hp: #../data/ontologies/hp.db
# Save DS 
path_to_ds: /data/results/comm_subset_cord-19_dataset.csv
path_to_ds_kb: /data/results/comm_subset_cord-19_dataset_kb.csv
path_to_ds_kb_all: /data/results/comm_subset_cord-19_dataset_kb_all.csv
# Save metadata about process
path_to_info: ../data/info_process_rs.txt


# mysql info
[MYSQL]
host:  172.17.0.13
user: root
password: 1234

# database
[DB]
database: entities_sim_cord19_rs 
table: similarity

