[info]
# Input data to run download dataset and move between folders after cleaning, steeming. 
# Mantainer: matilde.pato
# Version 1.0
# Date: May, 23rd 2022


# Information about dataset from 'https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/'
[DS]
date: 2020-05-19
docname: document_parses.tar.gz
tar_document: cord-19_2020-05-19.tar.gz

# Language, write all language separated by ","
[LANG]
lang: en

# Path of several files
[PATH]
pdf_dir: /data/document_parses/pdf_json/
pmc_dir: /data/document_parses/pmc_json/
path_original_file: /data/comm_use_subset/
path_metadata: /data/metadata.csv
path_metadata_new: /data/metadata_new.csv
path2blacklist: /data/blacklists/blacklist.txt
path2garbage: ../data/garbage/
list_of_downloaded_file: /data/list_json_files.csv

# Save metadata about process
path_to_info: ../data/info_process.txt

# Transfer files: copy or move option
[TRANSFER]
option: copy
