[info]

#path_to_original_json_folder = /path/to/original_data/folder/
#path_to_entities_json_folder =  /path/to/entities_data/folder/

#path_to_csv: /path/to/csv.csv

# Dataset
path_to_original_json_folder: ../data/comm_use_subset/
path_to_entities_json_folder: ../data/comm_use_subset_entities/

#Blacklist  ../blacklists/
path_to_blacklist: ../blacklists/blacklist_articles.txt

# Metadata file
path_to_metadata: /data/metadata_new.csv

# items list: uncomment item
item_prefix1: chebi
item_prefix2: do
#item_prefix3: go
#item_prefix4: hp

# Ontologies path
path_chebi: /data/ontologies/chebi_lite.owl
path_do: /data/ontologies/doid.owl
#path_go: ../data/ontologies/go.owl
#path_hp: ../data/ontologies/hp.owl

# Save DS
#path_to_cord_ds: /data/results/comm_subset_cord-19_dataset.csv
#path_to_cord_userid: /data/results/comm_subset_cord-19_dataset_userid.csv
#path_to_cord_all: /data/results/comm_subset_cord-19_dataset_all2.csv
path_ds: ../data/results/comm_subset_medicine_dataset.csv
path_next_stage: ../../KB/data

# Save metadata about process
path_to_info: ../data/info_process_rs.txt